#+TITLE: December
#+DESCRIPTION: Converts Emacs Org file to HTML
#+AUTHOR: Kyle Gortych
#+SETUPFILE: https://fniessen.github.io/org-html-themes/org/theme-readtheorg.setup
#+OPTIONS: num:nil

@@html:<a href="index.html" target="_self">Home</a>@@
@@html:<a href="january.html" target="_self">January</a>@@
@@html:<a href="february.html" target="_self">February</a>@@
@@html:<a href="march.html" target="_self">March</a>@@
@@html:<a href="april.html" target="_self">April</a>@@
@@html:<a href="may.html" target="_self">May</a>@@
@@html:<a href="june.html" target="_self">June</a>@@
@@html:<a href="july.html" target="_self">July</a>@@
@@html:<a href="august.html" target="_self">August</a>@@
@@html:<a href="september.html" target="_self">September</a>@@
@@html:<a href="october.html" target="_self">October</a>@@
@@html:<a href="november.html" target="_self">November</a>@@
# @@html:<a href="december.html" target="_self">December</a>@@

# org file tables in Emacs features tab jumping and resizing columns. Use SPC m b - to insert table header under current cursor line.

+----------------------------------------------------------------------+
|                            December 2022                             |
+--------+--------+---------+-----------+----------+--------+----------+
| Sunday | Monday | Tuesday | Wednesday | Thursday | Friday | Saturday |
+--------+--------+---------+-----------+----------+--------+----------+
| Previous Month                        | 1        | 2      | 3        |
+--------+--------+---------+-----------+----------+--------+----------+
| 4      | 5      | 6       | 7         | 8        | 9      | 10       |
+--------+--------+---------+-----------+----------+--------+----------+
| 11     | 12     | 13      | 14        | 15       | 16     | 17       |
+--------+--------+---------+-----------+----------+--------+----------+
| 18     | 19     | 20      | 21        | 22       | 23     | 24       |
+--------+--------+---------+-----------+----------+--------+----------+
| 25     | 26     | 27      | 28        | 29       | 30     | 31       |
+--------+--------+---------+-----------+----------+--------+----------+

** Christmas
Christmas is an annual festival commemorating the birth of Jesus Christ, observed primarily on December 25 as a religious and cultural celebration among billions of people around the world. A feast central to the Christian liturgical year, it is preceded by the season of Advent or the Nativity Fast and initiates the season of Christmastide, which historically in the West lasts twelve days and culminates on Twelfth Night. Christmas Day is a public holiday in many countries, is celebrated religiously by a majority of Christians, as well as culturally by many non-Christians, and forms an integral part of the holiday season organized around it.
