#+TITLE: January
#+DESCRIPTION: Converts Emacs Org file to HTML
#+AUTHOR: Kyle Gortych
#+SETUPFILE: https://fniessen.github.io/org-html-themes/org/theme-readtheorg.setup
#+OPTIONS: num:nil

@@html:<a href="index.html" target="_self">Home</a>@@
# @@html:<a href="january.html" target="_self">January</a>@@
@@html:<a href="february.html" target="_self">February</a>@@
@@html:<a href="march.html" target="_self">March</a>@@
@@html:<a href="april.html" target="_self">April</a>@@
@@html:<a href="may.html" target="_self">May</a>@@
@@html:<a href="june.html" target="_self">June</a>@@
@@html:<a href="july.html" target="_self">July</a>@@
@@html:<a href="august.html" target="_self">August</a>@@
@@html:<a href="september.html" target="_self">September</a>@@
@@html:<a href="october.html" target="_self">October</a>@@
@@html:<a href="november.html" target="_self">November</a>@@
@@html:<a href="december.html" target="_self">December</a>@@

# org file tables in Emacs features tab jumping and resizing columns. Use SPC m b - to insert table header under current cursor line.

+----------------------------------------------------------------------+
|                            January 2022                              |
+--------+--------+---------+-----------+----------+--------+----------+
| Sunday | Monday | Tuesday | Wednesday | Thursday | Friday | Saturday |
+--------+--------+---------+-----------+----------+--------+----------+
| Previous Month                                            | 1        |
+--------+--------+---------+-----------+---------+---------+----------+
| 2      | 3      | 4       | 5         | 6       | 7       | 8        |
+--------+--------+---------+-----------+---------+---------+----------+
| 9      | 10     | 11      | 12        | 13      | 14      | 15       |
+--------+--------+---------+-----------+---------+---------+----------+
| 16     | 17     | 18      | 19        | 20      | 21      | 22       |
+--------+--------+---------+-----------+---------+---------+----------+
| 23     | 24     | 25      | 26        | 27      | 28      | 29       |
+--------+--------+---------+-----------+---------+---------+----------+
| 30     | 31     | Next Month                                         |
+--------+--------+----------------------------------------------------+

** New Year's Day
New Year's Day is a festival observed in most of the world on 1 January, the first day of the year in the modern Gregorian calendar. 1 January is also New Year's Day on the Julian calendar, but this is not the same day as the Gregorian one. Whilst most solar calendars (like the Gregorian and Julian) begin the year regularly at or near the northern winter solstice, cultures that observe a lunisolar or lunar calendar celebrate their New Year (such as the Chinese New Year and the Islamic New Year) at less fixed points relative to the solar year.

** Martin Luther King Jr. Day
Martin Luther King Jr. Day (officially Birthday of Martin Luther King, Jr.,[1] and sometimes referred to as MLK Day) is a federal holiday in the United States marking the birthday of Martin Luther King Jr. It is observed on the third Monday of January each year. Born in 1929, King's actual birthday is January 15 (which in 1929 fell on a Tuesday). The holiday is similar to holidays set under the Uniform Monday Holiday Act. The earliest Monday for this holiday is January 15 and the latest is January 21.

King was the chief spokesperson for nonviolent activism in the Civil Rights Movement, which protested racial discrimination in federal and state law. The campaign for a federal holiday in King's honor began soon after his assassination in 1968. President Ronald Reagan signed the holiday into law in 1983, and it was first observed three years later. At first, some states resisted observing the holiday as such, giving it alternative names or combining it with other holidays. It was officially observed in all 50 states for the first time in 2000.
