#+TITLE: November
#+DESCRIPTION: Converts Emacs Org file to HTML
#+AUTHOR: Kyle Gortych
#+SETUPFILE: https://fniessen.github.io/org-html-themes/org/theme-readtheorg.setup
#+OPTIONS: num:nil

@@html:<a href="index.html" target="_self">Home</a>@@
@@html:<a href="january.html" target="_self">January</a>@@
@@html:<a href="february.html" target="_self">February</a>@@
@@html:<a href="march.html" target="_self">March</a>@@
@@html:<a href="april.html" target="_self">April</a>@@
@@html:<a href="may.html" target="_self">May</a>@@
@@html:<a href="june.html" target="_self">June</a>@@
@@html:<a href="july.html" target="_self">July</a>@@
@@html:<a href="august.html" target="_self">August</a>@@
@@html:<a href="september.html" target="_self">September</a>@@
@@html:<a href="october.html" target="_self">October</a>@@
# @@html:<a href="november.html" target="_self">November</a>@@
@@html:<a href="december.html" target="_self">December</a>@@

# org file tables in Emacs features tab jumping and resizing columns. Use SPC m b - to insert table header under current cursor line.

+----------------------------------------------------------------------+
|                            November 2022                             |
+--------+--------+---------+-----------+----------+--------+----------+
| Sunday | Monday | Tuesday | Wednesday | Thursday | Friday | Saturday |
+--------+--------+---------+-----------+----------+--------+----------+
| Previous Month  | 1       | 2         | 3        | 4      | 5        |
+--------+--------+---------+-----------+----------+--------+----------+
| 6      | 7      | 8       | 9         | 10       | 11     | 12       |
+--------+--------+---------+-----------+----------+--------+----------+
| 13     | 14     | 15      | 16        | 17       | 18     | 19       |
+--------+--------+---------+-----------+----------+--------+----------+
| 20     | 21     | 22      | 23        | 24       | 25     | 26       |
+--------+--------+---------+-----------+----------+--------+----------+
| 27     | 28     | 29      | 30        | Next Month                   |
+--------+--------+---------+-----------+------------------------------+

** Veterans Day
Veterans Day (originally known as Armistice Day) is a federal holiday in the United States observed annually on November 11, for honoring military veterans of the United States Armed Forces (who were discharged under conditions other than dishonorable). It coincides with other holidays including Armistice Day and Remembrance Day which are celebrated in other countries that mark the anniversary of the end of World War I. Major hostilities of World War I were formally ended at the 11th hour of the 11th day of the 11th month of 1918 when the Armistice with Germany went into effect. At the urging of major U.S. veteran organizations, Armistice Day was renamed Veterans Day in 1954.

** Thanksgiving
Thanksgiving is a national holiday celebrated on various dates in the United States, Canada, Grenada, Saint Lucia, and Liberia. It began as a day of giving thanks for the blessing of the harvest and of the preceding year. Similarly named festival holidays occur in Germany and Japan. Thanksgiving is celebrated on the second Monday of October in Canada and on the fourth Thursday of November in the United States and around the same part of the year in other places. Although Thanksgiving has historical roots in religious and cultural traditions, it has long been celebrated as a secular holiday as well.
